pip3 install colorama
pip3 install os
pip3 install random
pip3 install datetime
pip3 install art
pip3 install webbrowser
pip3 install time
pip3 install getpass
pip3 install shutil
pip3 install g4f
pip3 install search
pip3 install requests